# Generated by Django 5.2.4 on 2025-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('note', 'Note')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insights', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
