# Generated by Django 5.2.4 on 2025-07-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contextentries',
            table='context_entries',
        ),
    ]
